#!/usr/bin/env python3
"""Generate src/xlsxedit/_ooxml_order.py from the vendored ECMA-376 schemas (maintainer tool).

Without arguments, rewrite the module. With --check, exit with status 1 when
the module differs from what the schemas produce.
"""

from __future__ import annotations

import argparse
import json
import sys
from functools import lru_cache
from pathlib import Path

from lxml import etree

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = ROOT / "schemas" / "transitional"
OUTPUT = ROOT / "src" / "xlsxedit" / "_ooxml_order.py"

_XSD_NS = "http://www.w3.org/2001/XMLSchema"

# (schema file, type name) for every table the module exports.
ORDER_TYPES: tuple[tuple[str, str], ...] = (
    ("sml.xsd", "CT_Worksheet"),
    ("sml.xsd", "CT_Stylesheet"),
    ("sml.xsd", "CT_Xf"),
    ("sml.xsd", "CT_Workbook"),
    ("sml.xsd", "CT_Table"),
    ("sml.xsd", "CT_TableColumn"),
    ("sml.xsd", "CT_Row"),
    ("sml.xsd", "CT_Cell"),
    ("sml.xsd", "CT_CfRule"),
    ("sml.xsd", "CT_ConditionalFormatting"),
    ("sml.xsd", "CT_DataValidation"),
    ("dml-spreadsheetDrawing.xsd", "CT_TwoCellAnchor"),
    ("dml-chart.xsd", "CT_Chart"),
    ("dml-chart.xsd", "CT_ChartSpace"),
)
ATTRIBUTE_DEFAULT_TYPES: tuple[tuple[str, str], ...] = (
    ("sml.xsd", "CT_Table"),
    ("sml.xsd", "CT_TableColumn"),
)
ENUM_TYPES: tuple[tuple[str, str], ...] = (
    ("sml.xsd", "ST_TableType"),
    ("sml.xsd", "ST_TotalsRowFunction"),
)

_HEADER = '''\
"""Child-element order, attribute defaults, and enumerations from ECMA-376.

Generated by ``scripts/gen_ooxml_order.py`` from the transitional schemas in
``schemas/transitional``. Do not edit; change the generator and rerun it.

``ORDER`` maps a complex type to the local names of its child elements in
schema sequence. The alternatives of an ``xsd:choice`` keep their schema
order; at most one of them occurs.
"""

from __future__ import annotations
'''


def _xsd(localname: str) -> str:
    return f"{{{_XSD_NS}}}{localname}"


@lru_cache(maxsize=None)
def _schema(filename: str) -> etree._Element:
    return etree.parse(str(SCHEMAS / filename)).getroot()


def _definition(filename: str, kind: str, name: str) -> etree._Element:
    for node in _schema(filename).iterchildren(_xsd(kind)):
        if node.get("name") == name:
            return node
    raise LookupError(f"{filename} defines no xsd:{kind} named {name!r}")


def _local(qualified: str) -> str:
    return qualified.rpartition(":")[2]


def _element_names(filename: str, particle: etree._Element) -> list[str]:
    """Names of the child elements a content model allows, in schema order."""
    names: list[str] = []
    for node in particle.iterchildren(etree.Element):
        kind = etree.QName(node).localname
        if kind in ("annotation", "attribute", "attributeGroup", "anyAttribute"):
            continue
        if kind == "element":
            names.append(node.get("name") or _local(node.get("ref")))
            continue
        if kind not in ("sequence", "choice", "group"):
            raise ValueError(f"unsupported xsd:{kind} in a content model")
        if node.get("maxOccurs", "1") != "1":
            raise ValueError(f"a repeating xsd:{kind} has no single child order")
        if kind == "group":
            node = _definition(filename, "group", _local(node.get("ref")))
        names.extend(_element_names(filename, node))
    return names


def child_order(filename: str, type_name: str) -> tuple[str, ...]:
    names = _element_names(filename, _definition(filename, "complexType", type_name))
    if len(set(names)) != len(names):
        raise ValueError(f"{type_name} names a child element twice")
    return tuple(names)


def attribute_defaults(filename: str, type_name: str) -> dict[str, str]:
    complex_type = _definition(filename, "complexType", type_name)
    return {
        attribute.get("name") or _local(attribute.get("ref")): attribute.get("default")
        for attribute in complex_type.iterchildren(_xsd("attribute"))
        if attribute.get("default") is not None
    }


def enumeration(filename: str, type_name: str) -> tuple[str, ...]:
    simple_type = _definition(filename, "simpleType", type_name)
    return tuple(node.get("value") for node in simple_type.iter(_xsd("enumeration")))


def _tuple_block(key: str, values: tuple[str, ...]) -> list[str]:
    return [f"    {json.dumps(key)}: (", *(f"        {json.dumps(v)}," for v in values), "    ),"]


def render() -> str:
    """Return the source of the generated module."""
    lines = [_HEADER, "ORDER: dict[str, tuple[str, ...]] = {"]
    for filename, type_name in ORDER_TYPES:
        lines += _tuple_block(type_name, child_order(filename, type_name))
    lines += ["}", "", "ATTRIBUTE_DEFAULTS: dict[str, dict[str, str]] = {"]
    for filename, type_name in ATTRIBUTE_DEFAULT_TYPES:
        lines.append(f"    {json.dumps(type_name)}: {{")
        for name, default in attribute_defaults(filename, type_name).items():
            lines.append(f"        {json.dumps(name)}: {json.dumps(default)},")
        lines.append("    },")
    lines += ["}", "", "ENUMS: dict[str, tuple[str, ...]] = {"]
    for filename, type_name in ENUM_TYPES:
        lines += _tuple_block(type_name, enumeration(filename, type_name))
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report a stale module with exit status 1 instead of rewriting it",
    )
    args = parser.parse_args(argv)
    source = render()
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else None
    if current == source:
        return 0
    if args.check:
        print(f"{OUTPUT.relative_to(ROOT)} is stale; run scripts/gen_ooxml_order.py", file=sys.stderr)
        return 1
    OUTPUT.write_text(source, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
